backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "site_content"
    label: "Contenido del sitio"
    files:

      # HEADER
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - { label: "Imagen de perfil", name: "header_profile_img", widget: "image" }
          - { label: "Título principal",  name: "header_title",       widget: "string" }
          - { label: "Subtítulo",         name: "header_subtitle",    widget: "string" }

      # PORTFOLIO (AHORA correctamente indentado bajo files:)
      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio.md"
        fields:
          - label: "Imagen 1"
            name: "portfolio_img_1"
            widget: "select"
            options:
              - "/assets/img/portfolio-1.jpg"
              - "/assets/img/portfolio-2.jpg"
              - "/assets/img/portfolio-3.jpg"
              - "/assets/img/portfolio-4.jpg"
          - label: "Imagen 2"
            name: "portfolio_img_2"
            widget: "select"
            options:
              - "/assets/img/portfolio-1.jpg"
              - "/assets/img/portfolio-2.jpg"
              - "/assets/img/portfolio-3.jpg"
              - "/assets/img/portfolio-4.jpg"
          - label: "Imagen 3"
            name: "portfolio_img_3"
            widget: "select"
            options:
              - "/assets/img/portfolio-1.jpg"
              - "/assets/img/portfolio-2.jpg"
              - "/assets/img/portfolio-3.jpg"
              - "/assets/img/portfolio-4.jpg"
          - label: "Imagen 4"
            name: "portfolio_img_4"
            widget: "select"
            options:
              - "/assets/img/portfolio-1.jpg"
              - "/assets/img/portfolio-2.jpg"
              - "/assets/img/portfolio-3.jpg"
              - "/assets/img/portfolio-4.jpg"

      # … el resto de tus archivos (About, Footer, Services, etc.)
