backend:
  name: github
  repo: "Sebsatian2025/democms"
  branch: "main"
  auth_type: authorization_code
  client_id: Ov23liXrrcUpP0ly32X3
  media_folder: "../assets/img" # <-- Ahora apunta a la carpeta de la raíz

  # Las siguientes líneas son necesarias para authorization_code
  base_url: "https://sebastiandemo.netlify.app/.netlify/functions"
  auth_endpoint: "auth"

collections:
  - name: "site_content"
    label: "Contenido del sitio"
    files:
      # HEADER
      - label: "Header"
        name: "header"
        file: "../content/header.md" # <-- También corregida la ruta para content/
        fields:
          - { label: "Imagen de fondo", name: "header_background", widget: "image" }
          - { label: "Título principal", name: "header_title", widget: "string" }
          - { label: "Subtítulo", name: "header_subtitle", widget: "string" }
          - { label: "Texto del botón", name: "header_button_text", widget: "string" }
          - { label: "Enlace del botón", name: "header_button_link", widget: "string" }

      # PORTFOLIO
      - label: "Portfolio"
        name: "portfolio"
        file: "../content/portfolio.md" # <-- También corregida la ruta para content/
        fields:
          - { label: "Imagen 1", name: "portfolio_img_1", widget: "image" }
          - { label: "Título imagen 1", name: "portfolio_title_1", widget: "string" }
          - { label: "Descripción imagen 1", name: "portfolio_desc_1", widget: "string" }
          - { label: "Imagen 2", name: "portfolio_img_2", widget: "image" }
          - { label: "Título imagen 2", name: "portfolio_title_2", widget: "string" }
          - { label: "Descripción imagen 2", name: "portfolio_desc_2", widget: "string" }
          - { label: "Imagen 3", name: "portfolio_img_3", widget: "image" }
          - { label: "Título imagen 3", name: "portfolio_title_3", widget: "string" }
          - { label: "Descripción imagen 3", name: "portfolio_desc_3", widget: "string" }
          - { label: "Imagen 4", name: "portfolio_img_4", widget: "image" }
          - { label: "Título imagen 4", name: "portfolio_title_4", widget: "string" }
          - { label: "Descripción imagen 4", name: "portfolio_desc_4", widget: "string" }

