backend:
  name: github
  repo: "Sebsatian2025/democms"
  branch: "main"
  auth_type: implicit
  # Este es el ID de tu app de OAuth de GitHub.
  # El navegador puede manejarlo de forma segura.
  client_id: "Ov23liXrrcUpP0ly32X3"

collections:
  - name: "site_content"
    label: "Contenido del sitio"
    files:
      # HEADER
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - { label: "Imagen de fondo", name: "header_background", widget: "image" }
          - { label: "Título principal", name: "header_title", widget: "string" }
          - { label: "Subtítulo", name: "header_subtitle", widget: "string" }
          - { label: "Texto del botón", name: "header_button_text", widget: "string" }
          - { label: "Enlace del botón", name: "header_button_link", widget: "string" }

      # PORTFOLIO
      - label: "Portfolio"
        name: "portfolio"
        file: "content/portfolio.md"
        fields:
          - { label: "Imagen 1", name: "portfolio_img_1", widget: "image" }
          - { label: "Título imagen 1", name: "portfolio_title_1", widget: "string" }
          - { label: "Descripción imagen 1", name: "portfolio_desc_1", widget: "string" }
          - { label: "Imagen 2", name: "portfolio_img_2", widget: "image" }
          - { label: "Título imagen 2", name: "portfolio_title_2", widget: "string" }
          - { label: "Descripción imagen 2", name: "portfolio_desc_2", widget: "string" }
          - { label: "Imagen 3", name: "portfolio_img_3", widget: "image" }
          - { label: "Título imagen 3", name: "portfolio_title_3", widget: "string" }
          - { label: "Descripción imagen 3", name: "portfolio_desc_3", widget: "string" }
          - { label: "Imagen 4", name: "portfolio_img_4", widget: "image" }
          - { label: "Título imagen 4", name: "portfolio_title_4", widget: "string" }
          - { label: "Descripción imagen 4", name: "portfolio_desc_4", widget: "string" }

      # ... El resto de collections igual que tu config original
