backend:
  name: github
  repo: "Sebsatian2025/democms"
  branch: "main"
  auth_type: authorization_code
  client_id: "Ov23liXrrcUpP0ly32X3"
  base_url: "https://sebastiandemo.netlify.app/.netlify/functions"
  auth_endpoint: "callback"

media_folder: "assets/images"

collections:
  - name: "site_content"
    label: "Contenido del sitio"
    files:
      - label: "Header"
        name: "header"
        file: "content/header.md"
        fields:
          - { label: "Imagen de fondo",    name: "header_background",    widget: "image"  }
          - { label: "Título principal",   name: "header_title",         widget: "string" }
          - { label: "Subtítulo",          name: "header_subtitle",      widget: "string" }
          - { label: "Texto del botón",    name: "header_button_text",   widget: "string" }
          - { label: "Enlace del botón",   name: "header_button_link",   widget: "string" }
